const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const Application = require('../models/Application');
const AppUser = require('../models/AppUser');
const LicenseKey = require('../models/LicenseKey');
const { generateLicenseKey } = require('../utils/keyGenerator');
const { safeEqual } = require('../utils/security');
const { userLookupFilter, revealLicense, revealUser } = require('../utils/fieldCrypto');
const { resetDeviceBinding } = require('../utils/hwidFingerprint');

const notFound = (res) => res.status(404).json({ success: false, message: 'Not found' });

const botProtect = (req, res, next) => {
  const secret = req.headers['x-bot-secret'] || '';
  const expected = process.env.BOT_SECRET || '';

  if (!expected || expected.length < 32 || !safeEqual(secret, expected)) {
    return notFound(res);
  }
  next();
};

const resolveApp = async (appId) => {
  if (!appId) return null;
  if (mongoose.Types.ObjectId.isValid(appId)) {
    const byId = await Application.findById(appId);
    if (byId) return byId;
  }
  return Application.findOne({ appId: String(appId).toUpperCase() });
};

const assertBotAppAllowed = (app) => {
  const raw = (process.env.BOT_ALLOWED_APP_IDS || '').trim();
  if (process.env.NODE_ENV === 'production' && !raw) return false;
  if (!raw) return true;
  const allow = new Set(
    raw.split(',').map((s) => s.trim().toUpperCase()).filter(Boolean)
  );
  if (!allow.size) return process.env.NODE_ENV !== 'production';
  return allow.has(String(app.appId || '').toUpperCase())
    || allow.has(String(app._id || ''));
};

router.use(botProtect);

router.post('/gen-key', async (req, res) => {
  try {
    const { appId, duration, note } = req.body;
    if (!appId) return notFound(res);

    const app = await resolveApp(appId);
    if (!app || !assertBotAppAllowed(app)) return notFound(res);

    const safeDuration = Math.min(Math.max(Number(duration) || 30, 0), 3650);

    const key = await LicenseKey.create({
      app: app._id,
      key: generateLicenseKey(app.keyPrefix),
      duration: safeDuration,
      note: String(note || 'Generated by Bot').substring(0, 200),
    });

    res.json({ success: true, key: revealLicense(key) });
  } catch (e) {
    console.error('[bot/gen-key]', e.message);
    return notFound(res);
  }
});

router.post('/reset-hwid', async (req, res) => {
  try {
    const { appId, username } = req.body;
    if (!appId || !username) return notFound(res);

    const app = await resolveApp(appId);
    if (!app || !assertBotAppAllowed(app)) return notFound(res);

    const user = await AppUser.findOne(userLookupFilter(app._id, username)).select('_id');
    if (!user) return notFound(res);

    const result = await resetDeviceBinding({ appId: app._id, userId: user._id });
    if (!result.ok) return notFound(res);

    res.json({ success: true, hwid: null, message: 'HWID reset — user must login again' });
  } catch (e) {
    console.error('[bot/reset-hwid]', e.message);
    return notFound(res);
  }
});

router.get('/user-info/:appId/:username', async (req, res) => {
  try {
    const app = await resolveApp(req.params.appId);
    if (!app || !assertBotAppAllowed(app)) return notFound(res);

    const user = await AppUser.findOne(userLookupFilter(app._id, req.params.username))
      .select('status subscriptionExpire hwid pcName lastSeen');

    if (!user) return notFound(res);
    res.json({
      success: true,
      user: {
        username: revealUser(user),
        status: user.status,
      },
    });
  } catch (e) {
    console.error('[bot/user-info]', e.message);
    return notFound(res);
  }
});

router.post('/link', async (req, res) => {
  try {
    const { appId, username, discordId } = req.body;
    if (!appId || !username || !discordId) return notFound(res);

    const app = await resolveApp(appId);
    if (!app || !assertBotAppAllowed(app)) return notFound(res);

    const user = await AppUser.findOneAndUpdate(
      userLookupFilter(app._id, username),
      { discordId: String(discordId).trim() },
      { new: true }
    );
    if (!user) return notFound(res);
    res.json({ success: true, message: 'Linked successfully' });
  } catch (e) {
    console.error('[bot/link]', e.message);
    return notFound(res);
  }
});

router.all('*', (_req, res) => notFound(res));

module.exports = router;
